import time
print()
print()
print()
print()
print()
print()
print()
print()
print(' ------------------------------------------------------ ')
time.sleep(0.2)
print('│  .oooooo.                                            │ ')
time.sleep(0.2)
print('│ d8P\'  `Y8b                                           │ ')
time.sleep(0.2)
print('│888            .ooooo.  ooo. .oo.    .ooooo.          │ ')
time.sleep(0.2)
print('│888           d88\' `88b `888P\"Y88b  d88\' `88b         │ ')
time.sleep(0.2)
print('│888     ooooo 888   888  888   888  888ooo888         │ ')
time.sleep(0.2)
print('│`88.    .88\'  888   888  888   888  888    .o         │ ')
time.sleep(0.2)
print('│ `Y8bood8P\'   `Y8bod8P\' o888o o888o `Y8bod8P\'         │ ')
time.sleep(0.2)
print('│					               │')
time.sleep(0.2)
print('│------------------------------------------------------│')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                      Credits                         │')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                                                      │')
time.sleep(0.2)
print('│                                                      │')
time.sleep(0.2)
print('│                                                      │')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                      Main Coding                     │')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                     Andy                             │')
time.sleep(0.2)
print('│                     Swum                             │')
time.sleep(0.2)
print('│                     Jonathan                         │')
time.sleep(0.2)
print('│                                                      │')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                 Singleplayer Coding                  │')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                     Andy                             │')
time.sleep(0.2)
print('│                     Swum                             │')
time.sleep(0.2)
print('│                     Jonathan                         │')
time.sleep(0.2)
print('│                                                      │')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                    Network Coding                    │')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                     Andy                             │')
time.sleep(0.2)
print('│                     Swum                             │')
time.sleep(0.2)
print('│                     Jonathan                         │')
time.sleep(0.2)
print('│                                                      │')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                      Storyline                       │')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                     Andy                             │')
time.sleep(0.2)
print('│                     Swum                             │')
time.sleep(0.2)
print('│                     Jonathan                         │')
time.sleep(0.2)
print('│                     Deadifyed                        │')
time.sleep(0.2)
print('│                                                      │')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                      Art&Animations                  │')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                     Andy                             │')
time.sleep(0.2)
print('│                     Swum                             │')
time.sleep(0.2)
print('│                     Jonathan                         │')
time.sleep(0.2)
print('│                                                      │')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                   Special Thanks to                  │')
time.sleep(0.2)
print('│             ----------------------------             │')
time.sleep(0.2)
print('│                     Tom W.                           │')
time.sleep(0.2)
print('│                                                      │')
time.sleep(0.2)
print('│                                                      │')
time.sleep(0.2)
print('│  .oooooo.                                            │ ')
time.sleep(0.2)
print('│ d8P\'  `Y8b                                           │ ')
time.sleep(0.2)
print('│888            .ooooo.  ooo. .oo.    .ooooo.          │ ')
time.sleep(0.2)
print('│888           d88\' `88b `888P\"Y88b  d88\' `88b         │ ')
time.sleep(0.2)
print('│888     ooooo 888   888  888   888  888ooo888         │ ')
time.sleep(0.2)
print('│`88.    .88\'  888   888  888   888  888    .o         │ ')
time.sleep(0.2)
print('│ `Y8bood8P\'   `Y8bod8P\' o888o o888o `Y8bod8P\'         │ ')
time.sleep(0.2)
print('│					               │')
time.sleep(0.2)
print('│                                                      │')
time.sleep(0.2)
print('│ Gone 2012 All rights reserved                        │')
time.sleep(0.2)
print('│                                                      │')
time.sleep(0.2)
print(' ------------------------------------------------------ ')
time.sleep(0.2)
print()
print()
print()
print()
print(' --------------------------')
print('1 Type \'Quit\' to go back  1')
print(' --------------------------')
input()
